#!/usr/bin/env bash
###############################################################################
# lib/config_proxy.sh — генерация Python-конфига для alexbers/mtprotoproxy
#
# Конфиг для каждого домена: config/proxy-<normalized_domain>.py
# Содержит список всех секретов пользователей для этого домена.
###############################################################################
set -euo pipefail

# shellcheck source=lib/util.sh
source "${MTPX_ROOT}/lib/util.sh"
# shellcheck source=lib/secret.sh
source "${MTPX_ROOT}/lib/secret.sh"

# ─────────────────────────────────────────────────────────────────────────────
# generate_proxy_config — создать Python-конфиг для домена
# ─────────────────────────────────────────────────────────────────────────────
# generate_proxy_config <domain>
#
# Генерирует конфиг в config/proxy-<normalized_domain>.py
# Формат конфига — Python-словарь, совместимый с alexbers/mtprotoproxy.
# ─────────────────────────────────────────────────────────────────────────────
generate_proxy_config() {
  local domain="$1"
  local norm
  norm=$(normalize_domain "$domain")
  local config_file="${CONFIG_DIR}/proxy-${norm}.py"

  # Получаем все активные секреты для домена: secret,user_id
  local secrets
  secrets=$(secrets_active_for_domain "$domain" 2>/dev/null || echo "")

  if [[ -z "$secrets" ]]; then
    # Нет секретов — создаём заглушку с предупреждением
    local tmp
    tmp="$(mktemp "${config_file}.tmp.XXXXXX")"
    cat > "$tmp" <<'HEADER'
# MTProxy config — generated by mtpx
# WARNING: No secrets configured. Add users: mtpx user add <name>
HEADER
    printf '\nPORT = 443\nUSERS = []\nTLS = True\nTLS_DOMAIN = "%s"\nTAG = ""\n' "$domain" >> "$tmp"
    chmod 600 "$tmp"
    mv -f "$tmp" "$config_file"
    log_warn "Нет активных секретов для '${domain}' — конфиг создан, но USERS пуст"
    return 1
  fi

  # Генерируем Python-конфиг
  local tmp
  tmp="$(mktemp "${config_file}.tmp.XXXXXX")"

  cat > "$tmp" <<'HEADER'
# MTProxy config — generated by mtpx
# Format: alexbers/mtprotoproxy

HEADER

  # Порт — вычисляем из существующего контейнера или берём default
  local port
  local cname
  cname=$(container_name_for_domain "$domain" 2>/dev/null || echo "")
  if [[ -n "$cname" ]]; then
    port=$(docker_container_port "$cname" 2>/dev/null || echo "443")
  else
    port="443"
  fi

  # Секреты
  local secret_list=""
  local first=true
  while IFS=',' read -r secret user_id; do
    [[ -z "$secret" ]] && continue
    if $first; then
      secret_list="\"${secret}\""
      first=false
    else
      secret_list="${secret_list}, \"${secret}\""
    fi
  done <<< "$secrets"

  cat >> "$tmp" <<EOF
# Domain: ${domain}
PORT = ${port}
USERS = [${secret_list}]
TLS = True
TLS_DOMAIN = "${domain}"
TAG = ""
EOF

  chmod 600 "$tmp"
  mv -f "$tmp" "$config_file"
  log_info "Конфиг создан: proxy-${norm}.py (${secret_list//,/} секреты)"
}

# ─────────────────────────────────────────────────────────────────────────────
# remove_proxy_config — удалить конфиг домена
# ─────────────────────────────────────────────────────────────────────────────
remove_proxy_config() {
  local domain="$1"
  local norm
  norm=$(normalize_domain "$domain")
  local config_file="${CONFIG_DIR}/proxy-${norm}.py"

  if [[ -f "$config_file" ]]; then
    rm -f "$config_file"
    log_info "Конфиг удалён: proxy-${norm}.py"
  fi
}
